# Generated by Django 4.0.5 on 2022-12-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=30)),
                ('mot_de_passe', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'Utilisateurs',
            },
        ),
    ]
