# Generated by Django 4.1.4 on 2022-12-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_utilisateurs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='image',
            field=models.ImageField(blank=True, default='pp.png', upload_to=''),
        ),
    ]
